// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiRFo_c5PrNUYlFd9hRRFG1gCjGqck0tw',
    appId: '1:1080513248428:web:da34dcaa3a87ef79747309',
    messagingSenderId: '1080513248428',
    projectId: 'cardiocare-database',
    authDomain: 'cardiocare-database.firebaseapp.com',
    storageBucket: 'cardiocare-database.appspot.com',
    measurementId: 'G-XTVPG88QJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVSagYg1wrT7Jy1FQk0M-1xfTr1NHnBGw',
    appId: '1:1080513248428:android:87e140f3976f55aa747309',
    messagingSenderId: '1080513248428',
    projectId: 'cardiocare-database',
    storageBucket: 'cardiocare-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDifrwdcV9gx0qXc1w5bmXRNSZgrpqFkLQ',
    appId: '1:1080513248428:ios:91a1b9db8881a196747309',
    messagingSenderId: '1080513248428',
    projectId: 'cardiocare-database',
    storageBucket: 'cardiocare-database.appspot.com',
    iosBundleId: 'com.example.cardiocare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDifrwdcV9gx0qXc1w5bmXRNSZgrpqFkLQ',
    appId: '1:1080513248428:ios:91a1b9db8881a196747309',
    messagingSenderId: '1080513248428',
    projectId: 'cardiocare-database',
    storageBucket: 'cardiocare-database.appspot.com',
    iosBundleId: 'com.example.cardiocare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiRFo_c5PrNUYlFd9hRRFG1gCjGqck0tw',
    appId: '1:1080513248428:web:466c9d5035046b9c747309',
    messagingSenderId: '1080513248428',
    projectId: 'cardiocare-database',
    authDomain: 'cardiocare-database.firebaseapp.com',
    storageBucket: 'cardiocare-database.appspot.com',
    measurementId: 'G-6F2WB4CMP6',
  );

}