// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMtLZkdHtaFfagBSOQYLDiN1VY5UWk71w',
    appId: '1:605745330694:web:94dc9d0357163650ff6187',
    messagingSenderId: '605745330694',
    projectId: 'cardiocare-data',
    authDomain: 'cardiocare-data.firebaseapp.com',
    storageBucket: 'cardiocare-data.appspot.com',
    measurementId: 'G-2MSGTQ6QD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtSmR5uADyWhVIEYB23iBrKuSybF-YlZI',
    appId: '1:605745330694:android:b83e9b2186313e95ff6187',
    messagingSenderId: '605745330694',
    projectId: 'cardiocare-data',
    storageBucket: 'cardiocare-data.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRR0pC7nqQH1HFbiWtxYHzaIJDXCOsEWQ',
    appId: '1:605745330694:ios:5b6b8719972ff39dff6187',
    messagingSenderId: '605745330694',
    projectId: 'cardiocare-data',
    storageBucket: 'cardiocare-data.appspot.com',
    iosBundleId: 'com.example.cardiocare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRR0pC7nqQH1HFbiWtxYHzaIJDXCOsEWQ',
    appId: '1:605745330694:ios:5b6b8719972ff39dff6187',
    messagingSenderId: '605745330694',
    projectId: 'cardiocare-data',
    storageBucket: 'cardiocare-data.appspot.com',
    iosBundleId: 'com.example.cardiocare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMtLZkdHtaFfagBSOQYLDiN1VY5UWk71w',
    appId: '1:605745330694:web:20968fbcc1258b97ff6187',
    messagingSenderId: '605745330694',
    projectId: 'cardiocare-data',
    authDomain: 'cardiocare-data.firebaseapp.com',
    storageBucket: 'cardiocare-data.appspot.com',
    measurementId: 'G-C6NDFEQKSF',
  );
}
